### PR TITLE
Possibility to pass a function as title or label.

### PR DESCRIPTION
**Pull request by g-adolph**
The main goal of this request is to be able to use vue-i18n in any table header.

### CODE REVIEW

**Comment by kenberkeley** [comment]
i18n is an independent function and it has nothing to do with Datatable

**Comment by kenberkeley** [comment]
https://github.com/OneWayTech/simplest-i18n

**Comment by g-adolph** [comment]
Sorry, I mentioned the i18n to give as an example of use. In fact the great benefit is if you have an external source to set your titles, they are no longer static, since use title as a string generates a static string.

**Comment by kenberkeley** [comment]
it always has a translation map...

**Comment by kenberkeley** [comment]
so you dont really need to integrate Datatable with i18n

**Pull request closed without merging**
